apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://platform-tempo.monitoring.svc.cluster.local:4317"
  DB_HOST: postgres
  DB_NAME: shop
  DB_STATEMENT_TIMEOUT_MS: "5000"
  REDIS_URL: redis://redis:6379/0
  INVENTORY_URL: http://inventory:8080
  CHECKOUT_URL: http://checkout:8080
  PAYMENTS_URL: http://payments:8080
  GATEWAY_URL: http://payment-gateway:8080
  PROMOTIONS_URL: http://promotions:8080
  FRONTEND_URL: http://frontend:8080
